repos:
-   repo: git://github.com/google/yapf
    rev: 261841c1ab8c6698c7fb58b9186e620c64b05243
    hooks:
    -   id: yapf
        files: ^(ptbtest|tests)/.*\.py$
-   repo: git://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        files: ^ptbtest/.*\.py$
        args:
        - --max-line-length=120
-   repo: git://github.com/pycqa/pylint
    rev: v2.17.0
    hooks:
    -   id: pylint
        files: ^ptbtest/.*\.py$
        args:
        - --errors-only
        - --disable=no-name-in-module,import-error
