language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
branches:
  only:
    - master
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install https://github.com/python-telegram-bot/python-telegram-bot/archive/master.zip -U
script:
  - nosetests -v  --with-coverage --cover-package=ptbtest/
after_success:
  coveralls
