language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "pypy3"
branches:
  only:
    - master
install:
  - pip install coveralls
  - pip install codecov
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - nose2 -v  --with-coverage
after_success:
  - coveralls
  - codecov
